#!/bin/bash
# Sets up a new remote feature branch with tracking
. "./gitreflow-common"

if [ "$1" != "" ]
then
  # Check for local and remote existing branches
  git push origin `git_current_branch`:refs/heads/"$1"
  git fetch origin
  git branch --track "$1" origin/"$1"
  git checkout "$1"
fi
