#!/usr/bin/env ruby
$: << File.expand_path(File.dirname(File.realpath(__FILE__)) + '/../lib')
require 'rubygems'
require 'git_reflow'

reflow_command = ARGV.shift
if reflow_command.nil? || GitReflow.workflow.commands[reflow_command.to_sym].nil?
  GitReflow.help
elsif ARGV.include? "--help"
  GitReflow.documentation_for_command(reflow_command)
else
  command_options = GitReflow.parse_command_options!(reflow_command)
  p "Run the FUCK out of this command: #{reflow_command} #{command_options}"
  GitReflow.public_send(reflow_command.to_sym, command_options)
end
