name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        ruby: ['2.6.6', '2.7.2', '3.0.0 ']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run Tests for Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
      run: bundle exec rake
